@extends('market.layouts.index_3_layout')

@section('content')

    <br>
    <div class="main-container container">
        <ul class="breadcrumb">
            <li><a href="{{url('/')}}"><i class="fa fa-home"></i></a></li>
            {{--<li><a href="#">Account</a></li>--}}
            {{--<li><a href="#">Page</a></li>--}}
            <li><a href="#">Terms of Use</a></li>
        </ul>

        <div class="row">
            <div id="content" class="col-sm-12" style=" height: 500px; overflow: scroll;">
                <h3><strong>SHOPAHOLICKS TERMS OF USE</strong></h3>
                {{--<p><strong>SHOPAHOLICKS PRIVACY POLICY</strong></p>--}}

                {{--<p><strong>Shopaholicks Terms of Use</strong></p>--}}
                <p>1.1 INTRODUCTION</p>
                <p>We at Shopaholicks are of the firm belief that startups and small businesses are the bedrock every industrialized nation. These startups and independent small businesses in their millions are made up of individuals and group from all around the world bubbling with innovation and creative ingenuity. It is in the expression of this creativity in the production, acquisition and selling of their products and services that form the pillars upon which prosperous nations are made. This is what we firmly believe at Shopaholicks. This drives our passion to champion the cause of promoting startups and small business by providing them with the platform to show the world their work.</p>
                <p>We encourage everyone to take advantage of the countless opportunities that we provide on our platform and be involved in every aspect of Shopaholicks- display your work, give feedback, write reviews, participate in forums, team up with other members to collaborate on projects, talk to each other and keep an eye out for new services we will continue to add.&nbsp;</p>
                <p>Exhibiting your products and services on shopaholicks exposes them to millions of people from all over the world and provides your business with limitless opportunity to grow and remain viable. This however bestows on you certain legal responsibilities. It is up to you to make sure you are acquainted to all of those responsibilities and to make yourself aware of the requirements of this document.<br /> It is important that you read and understand the agreement below. Using this website means you accept this agreement and any changes made after the commencement of use.</p>
                <p>&nbsp;</p>
                <p>Shopaholicks.com is a product of REX Inc., an Accra based limited liability company (sometimes herein &ldquo;shopaholicks,&rdquo; &ldquo;We&rdquo; or "Us") offers services through the domain www.shopaholics.com (sometimes herein the "Site"). Shopaholicks provides a web application ("Software") that allows a user to maintain a social user account as well as the option of creating an online shop through which they can sell products and services online. Shopaholicks also provides merchant services, including hosting of the online shop, site design, marketing services and other related services as may be offered from time to time (individually and collectively, "Services"). By using the Services offered through the Site, you ("User" or "You," or &ldquo;Your&rdquo; which collectively includes You and any other person or entity on whose behalf You may be acting) are accepting and agreeing to the terms of use ("Terms") set forth below which will constitute a binding agreement between You and Shopaholicks ("Agreement").</p>
                <p>By using the Services of the Site, You are accepting and agreeing to the terms of the Shopaholicks Privacy Policy ("Privacy Agreement"), which You acknowledge You have read and fully understand. Also, if You sell Products or services through an online store on this Site, as described elsewhere, You must agree to the terms of the Shopaholicks Shop Owner's Agreement (&ldquo;shop Owner's Agreement"). Each shop owner will have their own online shop (&ldquo;Shop&rdquo;) from which it will sell its Products and services. In the event You buy Products or services through a store on this Site, Your purchase of Products or services through such a store will constitute Your agreement to comply with the terms applicable to a buyer of Products or services ("Buyer&rsquo;s Agreement"). By agreeing to be bound by the terms of this Agreement, You are acknowledging You have read and agree to be bound by the Shop Owner's Agreement and/or the Buyer&rsquo;s Agreement, as the case may be.</p>
                <p>You agree to comply with and be bound by the following Terms:</p>
                <p><br /> Shopaholicks serves as an online marketplace to allow qualifying users to offer, sell and purchaser Products and services for an agreed upon price. Shopaholicks has no involvement in the consummation of a contract between a seller and a buyer. Accordingly, Shopaholicks has no liability or responsibility for any matter arising out of the transaction between a seller and a buyer. You should be comfortable in all respects with a seller before You purchase Products from the Site.</p>
                <p>Our services are available only to, and may only be used by, individuals who can form legally binding contracts under applicable law. Our services are not available to persons under 18 years of age.<br /> If you are under 18, you may use Shopaholicks only with the permission and supervision of a responsible adult (parent or legal guardian). This is for legal reasons, not because we think kids or teens are any less creative or capable. It may be a good idea to give children space in your own online shop if they wish to sell their products or services.</p>
                <p>You consent to receive communications from Us by e-mail. When registering as a seller/user(buyer) you will be automatically subscribed to receive our 'user newsletter', which outlines important news, such as new features, blog posts that will help you further your knowledge about selling and using online etc.&nbsp; Each email has an 'unsubscribe' link at the bottom of the email.&nbsp; If you don't want to receive these emails anymore, simply 'unsubscribe' via the link and you'll be taken off the list.&nbsp; You agree that all agreements, notices, disclosures and other communications that we provide to you by e-mail satisfy any legal requirement that such communications be in writing.</p>
                <p><br /> You may use the Services and the Site and the content owned and provided by Shopaholicks (singularly and collectively, the &ldquo;Shopaholicks Content") solely in connection with the intended purposes of the Site. No right, title or interest in any Shopaholicks Content is transferred to You. Shopaholicks retains all of its intellectual property rights in all Shopaholicks Content. Except as expressly authorized by this Agreement, or otherwise agreed to by Shopaholicks, You may not use, alter, copy, distribute, transmit, or otherwise appropriate any Shopaholicks Content obtained from the Site or the Service, except as expressly permitted by the Terms or as otherwise agreed to by Shopaholicks.</p>
                <p>You agree to use the Site for lawful purposes only. You agree not to take any action that might affect the security of the Site, render the Site partially or wholly inaccessible to others or otherwise negatively alter or damage the Site or the Shopaholicks Content. You agree not to add to, subtract from, or otherwise modify the Shopaholicks Content, or to attempt to access any Shopaholicks Content that is not intended for You. You agree not to use the Site in any manner that might interfere with the rights of third parties.<br /> </p>
                <p>All sellers/buyers should be aware that by making a purchase from an overseas seller, this transaction may incur import tariffs and charges and/or extra fees and duties dependent on the country in which the seller resides. Shopaholicks takes no responsibility for any such charges and as such it is incumbent upon the buyer in all circumstances to perform sufficient research into such matters prior to executing an international purchase.</p>
                <p><br /> While using the Site You will not:</p>
                <ol>
                    <li>Be false, misleading, inaccurate or include inaccurate, misleading or false information to a seller or on any Storefront which You maintain.</li>
                    <li>Act in a fraudulent way or become involved in the sale of stolen or counterfeit items.</li>
                    <li>Violate any local, state, federal or other applicable laws or the rights of third party parties.</li>
                    <li>Access or use the Site if You are not able to enter into legally binding agreements, are under the age of 18, or are temporarily or indefinitely suspended from the Site.</li>
                    <li>Fail to deliver payment for items purchased by You.</li>
                    <li>Fail to deliver items purchased from You if You are a Seller.</li>
                    <li>Infringe on another party&rsquo;s right, title and interest in and to their intellectual property including copyrights and trademarks.</li>
                    <li>Interfere with the sales of other online sellers in any way that injures, damages or negatively affects their use and enjoyment of the Site.</li>
                    <li>Be libelous or defamatory with any information posted on the Site.</li>
                    <li>Disseminate or display spam, chain letters or pyramid schemes.</li>
                    <li>Contain or transmit code or employ other actions which may harm Shopaholicks, the Site, the Shopaholicks Content or the interests or property of Shopaholicks users.</li>
                    <li>Copy, modify, or distribute content from the Site and/or Shopaholicks's copyrights and trademarks unless agreed to by Shopaholicks.</li>
                    <li>Collect information about users, including email addresses, without their consent.</li>
                    <li>Disseminate or display content or information that (a) is offensive or inflammatory, such as content that promotes racism, bigotry, hatred or physical harm of any kind against any group or individuals; (b) promotes illegal or unauthorized copy of another person's work, such as providing pirated computer programs or links to them, provides information to circumvent manufacture-installed copy-protect devices, or (c) provides pirated content or links to pirated content files.</li>
                    <li>Be obscene or post any information that contains pornography including child pornography. Mature content and profane language is not permitted in your username, shop title, welcome message, shop banner, avatar, item descriptions, profile page or anywhere else in your shop.</li>
                    <li>Violate the Seller's Agreement, as the case may be, if You are a seller.</li>
                    <li>Use any automated means to access the Site for any purpose without the express written permission of Shopaholicks.</li>
                    <li>Take any action that imposes or may impose an unreasonable or disproportionately large load on the Site or the ability to operate the Site as determined solely by Shopaholicks.</li>
                </ol>
                <p><br /> You are solely responsible for Your conduct while using the Site and for any and all information, store listings, advertisements, proposals, data, text, pictures, graphics, music, sights, sounds, depictions, images, photographs, audio, video and links (individually and collectively the &ldquo;Third Party Content&rdquo;) that You submit, post, and display on Shopaholicks. Further, as a Seller, You are solely responsible for each individual item of Third Party Content You display, link to or otherwise make available through the Site. You agree Shopaholicks has no control, and is not responsible for the Third Party Content appearing on the Site, and by using the Site or making purchases, You may encounter Third Party Content which You find is inaccurate, inappropriate, inflammatory or otherwise of concern to You.</p>
                <p>Here is a list of other prohibited items on Shopaholicks, even though they could possibly fit into one of our categories: a) Any item or service that violates applicable local, state, federal, or international law in regard to manufacturing, distributing, advertising, or transporting said item; b)Any product or service that Shopaholics.com determines to be inappropriate, harmful, fraudulent, or illegal; c) Dangerous Chemicals; d) Drugs; e) Explosives, Firearms and Fireworks; f) Stolen Items; g) Harmful, harassing, intimidating or defamatory materials, products or items; h) Hazardous materials, products, or items (for example: poisonous, explosive, flammable, corrosive etc.); i) Illegal, counterfeit or contraband items of any sort; j) Items, materials or products that are copyrighted, trademarked or patented by another party; k) items not in your possession or items you don't intend to deliver; l) Items or products that carry or transmit hidden code or signals with the intention of causing harm or tracking personal or transactional information of any sort; m) Items that violates Terms of Use n) Ivory or animal products from endangered species collected illegally; o) Misrepresented items or products; p) Personal data or information; q) Pirated materials; r) Pornography; s) Prostitution or other similar services; t) Protected antiquities; u) Tobacco</p>
                <p><br /> Shopaholicks makes no representation or warranty of any kind concerning the truth or accuracy or any other aspect of any information posted on this website by a User or any other information appearing at websites which are linked to in any Third Party Content. As a Seller, You agree that You are solely responsible for all content, material and Third Party Content appearing in Your storefront or in any links appearing within Your storefront. You agree that Shopaholicks does not pre-approve or review Third Party Content; however, Shopaholicks retains the right but not the obligation to deny, remove or alter any Third Party Content that appears on the Site, if in the sole discretion of Shopaholicks, such Third Party Content violates the Terms.</p>
                <p>This Site may contain links to other websites (&ldquo;linked websites&rdquo;). Those links are provided for convenience only and may not remain current.We are not responsible for the content or privacy practices associated with linked websites. Our links with linked websites should not be construed as an endorsement, approval or recommendation by us of the owners or operators of those linked websites, or of any information, graphics, materials, products or services referred to or contained on those linked websites, unless and to the extent stipulated to the contrary.</p>
                <p><br /> The Site and the Shopaholicks Content are protected by laws of Ghana, and belongs solely to Shopaholicks and REX Inc. You may not use, change or amend in any way the Site or the Shopaholicks Content without the prior written approval of Shopaholicks or/and REX Inc. As a Seller, You are granted a revocable non-exclusive license as part of the Shop Owner's Agreement, as the case may be, to utilize references to Shopaholicks and its logo in connection with linking to Your Storefront on the Site from other web pages.<br /> <br /> Shopaholicks does not claim ownership rights in Your Third Party Content. When You post or display Third Party Content on the Site, You grant to Shopaholicks a license to use and display the Third Party Content on the Site. You grant Shopaholicks a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, right to exercise the copyright, publicity, and database rights (but no other rights) You have in the Third Party Content, in any media now known or not currently known, with respect to Your Third Party Content. In the event a third party re-posts Your Third Party Content, You agreed to hold Shopaholicks harmless from any liability arising out of a dispute concerning the reposting of Your Third Party Content.<br /> <br /> If you are subscribed to a monthly/quarterly/yearly Shopaholicks service, at the beginning of each monthly/quarterly/yearly billing cycle during which you have been enabled to use the Shopaholicks marketplace, you will be charged the non-refundable Shopaholicks Monthly/quarterly/yearly Subscription Fee. You may disable the Marketplace from your Shopaholicks account by going to the Settings menu, setting the Marketplace to Off, and clicking the Save button. You may also send us a request to disable the Marketplace feature using the contact us form.</p>
                <p>Shopaholicks works hard to keep the Site operating for the benefit of its users. However, in the event of a problem, please contact Us at <a href="mailto:support@Shopaholicks.com">support@Shopaholicks.com</a>.</p>
                <p>SHOPAHOLICKS ON BEHALF OF ITS MEMBERS, DIRECTORS, OFFICERS, EMPLOYEES AND AGENTS, MAKES NO EXPRESS OR IMPLIED WARRANTIES, COVENANTS OR REPRESENTATIONS OF ANY KIND WITH RESPECT TO THE SITE, THE SERVICES, THE SHOPAHOLICKS CONTENT, THIRD PARTY CONTENT OR ANY OTHER CONTENT. SHOPAHOLICKS EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT, WITH REGARD TO THE SITE, THE SERVICES, THE SHOPAHOLICKS CONTENT, THIRD PARTY CONTENT AND ANY OTHER CONTENT, AND ANY PRODUCT OR SERVICE FURNISHED OR TO BE FURNISHED FROM OR ON THE SITE. SHOPAHOLICKS DOES NOT WARRANT: THAT THE FUNCTIONS PERFORMED BY THE SITE OR THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE; OR THAT DEFECTS IN THE SITE OR THE SERVICES WILL BE CORRECTED; OR -THE ACCURACY OR COMPLETENESS OF THE SHOPAHOLICKS CONTENT, THIRD PARTY CONTENT, OR ANY OTHER CONTENT; OR THAT ANY ERRORS IN THE SHOPAHOLICKS CONTENT, THIRD PARTY DATE OR OTHER CONTENT WILL BE CORRECTED. THE SITE, THE SERVICES, AND THE SHOPAHOLICKS CONTENT AND OTHER CONTENT ARE PROVIDED ON AN &ldquo;AS IS&rdquo;, &ldquo;WHERE IS&rdquo;, &ldquo;AS AVAILABLE&rdquo; AND &ldquo;WITH ALL FAULTS&rdquo; BASIS. SOME COUNTRIES DO NOT ALLOW THE DISCLAIMER OF IMPLIED WARRANTIES, SO THE FOREGOING DISCLAIMER MAY NOT APPLY TO YOU. THIS WARRANTY GIVES YOU SPECIFIC LEGAL RIGHTS AND YOU MAY ALSO HAVE OTHER LEGAL RIGHTS THAT VARY FROM COUNTRY TO COUNTRY.</p>
                <p>IN NO EVENT WILL SHOPAHOLICKS OR ITS MEMBERS, DIRECTORS, OFFICERS, EMPLOYEES AND AGENTS BE LIABLE FOR ANY DAMAGES WHATSOEVER, INCLUDING, BUT NOT LIMITED TO ANY DIRECT, INDIRECT, GENERAL, SPECIAL, COMPENSATORY, INCIDENTAL, CONSEQUENTIAL, EXEMPLARY OR OTHER DAMAGES ARISING OUT OF</p>
                <ul>
                    <li>YOUR CONDUCT OR ANYONE ELSE IN CONNECTION WITH USE OF THE SITE, THE SERVICES OR THIS AGREEMENT</li>
                    <li>INABILITY TO USE THE SITE, THE SERVICES, THE SHOPAHOLICKS CONTENT OR ANY OTHER CONTENT,</li>
                    <li>ANY TRANSACTION CONDUCTED THROUGH OR FACILITATED BY THE SITE; (IV) ANY CLAIM ATTRIBUTABLE TO ERRORS, OMISSIONS, OR OTHER INACCURACIES IN THE SITE, THE SERVICES, THE SHOPAHOLICKS CONTENT AND/OR ANY OTHER CONTENT, (V) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR INFORMATION, STOREFRONT OR DATA, OR</li>
                    <li>ANY OTHER MATTER RELATING TO THE SITE, THE SERVICES, SHOPAHOLICKS CONTENT OR ANY OTHER CONTENT, EVEN IF SHOPAHOLICKS HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IF YOU ARE DISSATISFIED WITH THE SITE, THE SERVICES, SHOPAHOLICKS CONTENT OR ANY OTHER CONTENT, OR WITH THE TERMS OF USE, YOUR SOLE AND EXCLUSIVE REMEDY IS TO CEASE USING THE SITE. SOME COUNTRIES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, AND THEREFORE SOME OF THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU. IN SUCH COUNTRIES SHOPAHOLICKS&rsquo;S LIABILITY IS LIMITED AND WARRANTIES ARE EXCLUDED TO THE GREATEST EXTENT PERMITTED BY LAW, BUT SHALL, IN NO EVENT, EXCEED GHC 100.00.</li>
                </ul>
                <p>IF YOU HAVE A DISPUTE WITH ONE OR MORE BUYERS, YOU RELEASE US (AND OUR MEMBERS, DIRECTORS, OFFICERS, EMPLOYEES AND AGENTS,) FROM CLAIMS, DEMANDS AND DAMAGES (ACTUAL AND CONSEQUENTIAL) OF EVERY KIND AND NATURE, KNOWN AND UNKNOWN, ARISING OUT OF OR IN ANY WAY CONNECTED WITH SUCH DISPUTE.<br /> <br /> YOU AGREE TO INDEMNIFY AND HOLD SHOPAHOLICKS (AND OUR MEMBERS, DIRECTORS, OFFICERS, EMPLOYEES AND AGENTS), HARMLESS FROM ANY CLAIM OR DEMAND, INCLUDING ATTORNEY FEES, MADE BY ANY THIRD PARTY DUE TO OR ARISING OUT OF (A) YOUR BREACH OF THIS AGREEMENT, OR YOUR VIOLATION OF ANY LAW OR THE RIGHTS OF A THIRD PARTY OR MADE BY ANY THIRD PARTY DUE TO OR ARISING OUT OF PRODUCTS OR SERVICES OFFERED FOR SALE OR ACTUALLY PURCHASED OR THE THIRD PARTY CONTENT OR OTHER CONTENT YOU SUBMIT, POST OR MAKE AVAILABLE THROUGH OR IN A SHOP AND (B) YOUR USE, MISUSE, OR INABILITY TO USE THE SITE, THE SERVICES, OR THE SHOPAHOLICKS CONTENT OR ANY VIOLATION BY YOU OF THIS AGREEMENT.<br /> <br /> YOU HEREBY FURTHER RELEASE SHOPAHOLICKS (AND OUR MEMBERS, DIRECTORS, OFFICERS, EMPLOYEES AND AGENTS) FOR ALL ACTIONS OR INACTIONS OF OTHER USERS, INCLUDING PRODUCTS AND SERVICES ADVERTISED OR SOLD. YOU AGREE THE SITE IS DESIGNED TO PERMIT PARTIES TO ENTER INTO TRANSACTIONS FOR ALL KINDS OF PRODUCTS AND SERVICES AND OTHER ACTIVITIES. SHOPAHOLICKS HAS NO CONTROL OVER AND DOES NOT GUARANTEE THE QUALITY, SAFETY OR LEGALITY OF THE PRODUCTS OR SERVICES ADVERTISED, THE TRUTH OR ACCURACY OF THE INFORMATION SET FORTH IN THE STOREFRONTS, THE ABILITY OF SELLERS TO SELL ITEMS, THE ABILITY OF BUYERS TO PAY FOR ITEMS, OR THAT A BUYER OR SELLER WILL ACTUALLY COMPLETE A TRANSACTION.</p>
                <p>This agreement is governed by the laws in force in Ghana. If a dispute arises between You and Shopaholicks, We will seek to resolve the dispute as quickly as commercially reasonable. Before resorting to legal proceedings, You must first contact Us directly and work with Us to resolve a dispute. If a dispute cannot be resolved by You and We, You will have the option to pursue a claim (a "Claim") against Shopaholicks in accordance with one of the options provided below or as We and You otherwise agree in writing.<br /> <br /> This Agreement shall be governed in all respects by the laws of the Republic of Ghana as they apply to agreements entered into and to be performed entirely within Ghana, without regard to conflict of law provisions.<br /> <br /> Option One - For any Claim (excluding claims for injunctive or other equitable relief) where the total amount of the award sought is less than GHC 20,000, the party requesting relief may elect to handle the Claim in a cost effective manner through binding non-appearance-based arbitration. In the event a party elects arbitration, they shall initiate such arbitration through an established alternative dispute resolution ("ADR") provider mutually agreed upon by the parties in Ghana. The ADR provider and the parties must comply with the following rules: a) the arbitration shall be conducted by telephone, online and/or be solely based on written submissions, the specific manner shall be chosen by the party initiating the arbitration; b) the arbitration shall not involve any personal appearance by the parties or witnesses unless otherwise mutually agreed by the parties; and c) the arbitrator&rsquo;s decision shall be final and not appealable to any court or any other tribunal or arbitrator(s), and shall be entered and enforceable as a judgment in a court of competent jurisdiction in Ghana.</p>
                <p>Option Two - For any other Claim other than a Claim which qualifies and is opted for by a party under option one above, such Claim may be submitted by either You or Us for arbitration in Ghana. Such arbitration proceedings will be conducted in Ghana and will be heard by one arbitrator in accordance with the then current commercial arbitrations rules of Ghana. Such arbitrator will be a lawyer of recognized standing and expertise in the area of commercial transactions.</p>
                <p>Shopaholicks retains the right to limit, suspend, or terminate Services for any user, prohibit access to the Site and take other actions deemed appropriate by Shopaholicks to keep users off the Site if We conclude a user is in violation of the Terms or other agreement with Shopaholicks.&nbsp;</p>
                <p>You and Shopaholicks are independent of one another and consequently, no agency, partnership, joint venture, employee-employer or franchiser-franchisee relationship is intended or created by this Agreement.<br /> <br /> These Terms are effective April 1, 2016, for current users, and upon use of the Site by a new user. We reserve the right to modify or terminate the Services for any reason, without notice, at any time. We reserve the right to alter or amend these Terms or other Site policies at any time. Any notices of termination or modification to the Services or the Terms will take effect when set forth on the Site. When using particular Services on the Site, You are subject to any unique posted policies or rules applicable to specific Services You use through the Site, which may be posted from time to time. All such policies or rules are hereby incorporated into this Agreement. This Agreement as supplemented by such other additional agreements for specific Services, sets forth the entire understanding and agreement between Us with respect to the subject matter hereof. If any of the terms or conditions herein shall be deemed invalid, void, or for any reason unenforceable, that term or condition shall be deemed severable and shall not affect the validity and enforceability of any remaining term or condition.</p>
                <p>Any responsibilities or obligations of a User which accrue or arise during the term of this Agreement shall survive the termination of this Agreement until fully satisfied by You.</p>
                <p>&nbsp;</p>

            </div>
        </div>
    </div>

    <br>
    <br>

@endsection